avinash201199/To-Do-List

- style.css
Input box and list item ...give a interactive look and changes the background colour with the top bar is looking good wth the bg
> make changes in css of todo-list

- style.css
Reverts avinash201199/To-Do-List#4
> Revert "make changes in css of todo-list"

- index.html
- style.css
> updated UI (heading font, rounded corners, color)

- index.html
- style.css
> corrected spelling

- README.md
Please review and merge.
Thanks!
> Added new icons and images.

- app.js
> fixing incomplete status filter

- index.html
#19 fix: The images set to the relative path was giving an issue.
> fix: social media icons in footer

- index.html
- style.css
Fixed  the issue The status filter dropdown disappears on small screen size
> Fixed  the issue The status filter dropdown disappears on small screen size

- style.css
> fixed the filter dropdown responsiveness issue

- app.js
Good evening ! 
Apparently the filter issue i opened got fixed before i got home to work on it , 
instead i rewrote the filterTodo function using es6 syntax and removed the repeated code used in the switch case method 
Hope that's fine by you
> Rewrote the filter function , using arrow function and DRY principle

- index.html
- style.css
Added Placeholder
Add Button Hover To Black
Dropdown Text as Black
Capitalisation
> UI Changes - Issue #8

- app.js
there was a curly brace missing on line 211
> fixed the issue #30

- app.js
- index.html
added a place holder for task name,
also i noticed when you refresh the page all task names change to [object Object]
> added placeholder and fixed page reload bug -- issue #32

- .vscode/settings.json
- style.css
Footer now moves down when list increases.
> Issue fixed.

- app.js
- index.html
- style.css
https://user-images.githubusercontent.com/62535464/135762484-98ded5ed-d386-427b-aa33-d29bf90c92d4.mp4
@avinash201199
> Changes done

- style.css
> Some design and aesthetic changes

- app.js
- index.html
- style.css
In reference to issue #39 
Not just error, but can call any one of three: red for error, blue for info, green for success.
More if you can add color classes. Message of any length can be passed.
> popup modal added

- index.html
> Improvised spelling issue #47

- app.js
- index.html
- style.css
> Feature added of day,date and time

- style.css
issue #51 
I just added few lines of code in style.css
> Fixed issue #51

- app.js
Doesn't allow whitespace as an input.
> whitespace input bug

- CONTRIBUTING.md
I have added the Contribution Guidelines file. thanks for giving me this opportunity
> added contribution guidelines

- index.html
- style.css
> #95 Fix alert position

- app.js
- index.html
- normalize.css
- style.css
Drastic update in design themes
> Design Update

- app.js
- Trim checks added in add / edit case.
- Duplicate function declaration removed.
- Updated edit logic
> Solves Bug for similar input

- app.js
- index.html
The autofocus attribute was not working as it should because it only works well on page load. So, i simply added this quality of life improvement using JS.
video —
https://user-images.githubusercontent.com/54097365/193453728-4d1fcb56-d3a5-471f-a9b8-2e4129a99792.mov
> added autofocus on new task input field

- app.js
- index.html
Changes
1. Commented the previous code for the time
2. Added Support for Time for any time zone ( The user who will use the ToDo List)
Change Image
> Added support for Global Time format instead just for IST

- index.html
- style.css
Before:
On hovering complete:
On hovering edit:
On hovering trash:
> Added hover states

- app.js
- index.html
> added a new feature to see date

- app.js
The page don't show message for users when clicked button deleted all task (when there are no items)
I add alert
> add alert msg 

- app.js
I have HTML encoded the input to prevent from XSS which fixes the issue #114
> updated app.js to fix XSS

- .vscode/settings.json
- index.html
- style.css
I have updated the footer, merge my PR
Issue #113
> UPDATED FOOTER 

- index.html
- particles.json
- style.css
Added non-interactive particles animation using particles-js library. Do add the hacktoberfest-accepted tag if no issues are found. Mention the issues if found any.
> hactoberfest2022 particles animation

- style.css
Added button CSS alignment for mobile view
> added code for button in Mobile view

- app.js
Hello, I changed the clock's time format, which seemed to have a bug. For example, if the current time is 3:05 PM and 2 seconds, the clock shows 15:5:2, and it's in 24-hour format. I have fixed it, now the time is in 12-hour format and attached screenshots of the same. 
The updated application's screenshot
> Changed time format

- assets/css/style.css
- assets/js/app.js
- index.html
The issue was with the delete all button which was there on screen even if the list was empty. The issue was fixed. A simple text is instead added to the empty space in the middle indicating if the list is empty or not.
> Issue #133 Fixed ( Delete All Button and Empty Space )

- assets/css/style.css
- index.html
I added a blinking heart animation to the footer section as a little adjustment.
> #149 Added a css animation of blinking heart on the footer

- assets/css/checklist.css
- assets/css/normalize.css
- index.html
- package-lock.json
- package.json
> change all font-family to the Montserrat

- assets/css/style.css
I have added a new animation to the buttons "Add new Task" and "All".
Please check and merge (Issue #181 )
https://user-images.githubusercontent.com/74719293/194695012-2d23467b-9b60-442d-9d0a-7f58d0e2e456.mp4
> New Animation Added

- assets/css/style.css
- assets/js/app.js
- index.html
Displayed time stamp in a togglable modal instead of an alertbox.
> Timestamp UI

- assets/css/style.css
- assets/js/app.js
- index.html
Uploading 2022-10-08 20-52-45.mp4…
> improved "delete-all" modal

- assets/js/app.js
Fixed: #187 
Screenshot:
1. Todos Added.
2. Task2 deleted. Refresh the page. Task2 deleted successfully.
> Delete todo issue fixed #187

- assets/css/style.css
- assets/js/app.js
- index.html
Added Tooltip for info icon. Made some CSS changes for the header.
> Harine hacktoberfest2022

- assets/css/style.css
- assets/js/app.js
Hey!, I made the card responsive,  also the background image was not fixed so I fixed it.
Before:
https://user-images.githubusercontent.com/71605903/195203182-4733f1af-390a-40f6-9873-5879e9de676d.mp4
After:
https://user-images.githubusercontent.com/71605903/195203904-fdcd7d76-fecb-4236-b4e4-757ba73580c0.mp4
This PR is a response to issue #208
> Make list card responsive

- assets/css/style.css
- assets/js/app.js
Reverts avinash201199/To-Do-List#217
> Revert "Make list card responsive"

- assets/css/style.css
- assets/js/app.js
- index.html
Reverts avinash201199/To-Do-List#209
> Revert "Harine hacktoberfest2022"

- assets/css/style.css
> add style changes for issue 212

- assets/css/style.css
- index.html
- package-lock.json
- package.json
Fade-down animation was applied to the model box while it was opening and the animate.css library for animation was implemented. The day date timer and Empty list text colors have been changed.
> #149 Integrated animate.css library for animation

- assets/js/app.js
Before changes:
After changes:
> showing &#45; if you add hyphen(-) in your text, Issue No- 222

- assets/js/app.js
- script.js
Corrected the todo functionality. The problem was in initializing the time in the addTodo function. Please add the hacktoberfest-accepted to my commit.
> corrected addTodo function in app.js

- assets/css/style.css
- assets/js/app.js
- index.html
Added Pop-up for congratulations when all the tasks have been completed!
> Added Pop-up!

- assets/css/style.css
> Fixed text visiblity in Popup Box

- assets/css/style.css
- index.html
For issue #238 , I have improved the styling of "the list is empty".
> improved the style

- README.md
I've added the images of every contributor in the readme file.
> Added Contributers section in readme file

- assets/css/style.css
Added background color on both the buttons which are "Add a new Task" and "All" when user hovers on these buttons they the color would turn from light blue to coral red and light red color which enhances User Interface.
Screenshot :-
> Changed the background color of buttons on hover so that it looks more fascinating and beautiful

- assets/js/app.js
Fixes issue #263 
I have solved the issue relating to the dark-mode. Kindly review it.
Added video for reference-
https://user-images.githubusercontent.com/99573906/196739332-c8f14873-f02c-45e6-8004-a8fea81b68b9.mp4
> solved Dark-mode issue 

- assets/css/style.css
- index.html
> Fix: Issue #259 Remove overlap of toggle button

- assets/js/app.js
Issue:- #265
Hi, @avinash201199 I fixed the time format... Convert it from milliseconds to proper date & time format.
> fixed alert time format

- assets/css/style.css
- index.html
> Improved the footer section

- assets/css/style.css
- index.html
> Restore the footer ui to the original ui

- assets/css/style.css
I have aligned the titlle with respect to the body content. Please consider my work and merge it under issue #295 under Hacktoberfest 2k22.
Thank You
> Aligned the title w.r.t the body component

- .vscode/settings.json
- assets/css/style.css
- assets/js/app.js
- index.html
Dark mode had many issues like not much good UI, return to light mode while adding a new task etc.
> fixed dark-mode issue

- assets/css/style.css
- assets/js/app.js
- index.html
Updated `app.js`, `index.html`.
Added new section to show aggregated data info like `Total Tasks`, `Remaing Tasks` and `Completed Tasks`.
None
> Aggregated tasks stats

- index.html
> changed text color for visiblity

- assets/css/style.css
- index.html
- Add the search feature in todo list
- Find the below screenshot for my implementation
Please review this PR for #316 @avinash201199 also add the label as "Hacktoberfest"
> [ADDED|SEARCH] add the search feature in todo list project

- assets/css/style.css
Fixes #319 
- It fixes the scroll button by changing its layout, size, and position.
- it also improves its design by changing the background of the scroll button and matching the website's theme.
It does not affect any current piece of code as it was checked by me.
> fixed scroll button

- assets/css/style.css
- assets/js/app.js
- index.html
closes #312 
**Description:**
This pull request adds a confirmation dialog for task deletion in the to-do list application. It prevents accidental task deletions by asking users to confirm their action.
**Changes Made:**
- Added JavaScript and CSS for the confirmation dialog.
- Implemented the dialog to appear when the "Trash-icon" is clicked.
- Provided options to confirm or cancel the deletion.
[Screencast from 22-10-23 02:47:04 AM IST.webm](https://github.com/avinash201199/To-Do-List/assets/140320635/e52233d3-630d-4b5f-b7a0-03cc8d922a59)
> Feature/confirmation dialog task deletion (fixes #312)

- assets/css/style.css
- index.html
- script.js
feature which allows user to prioritize the tasks based on his/her interest
@avinash201199
> prioritize task feature added

- assets/images/new-linkedIn.svg
- index.html
As you assigned my issue I have updated the LinkedIn icon . This icon looks same as the  original LinkedIn icon. 
Before: 
After :
> LinkedIn icon updated.

- Dockerfile
- README.md
Implemented Docker containerization to facilitate the deployment process and ensure consistent environments across different stages of development and production.
> Added docker containerizarion

- assets/css/style.css
- index.html
Issue : #339
I added a search button in the search field.
Before:
After:
> Added search icon

- index.html
Integrated AOS (Animate On Scroll) library into the index page for improved scroll animations.
Updated the index.html file to include instructions on using AOS.
> Scroll-Animation added

- index.html
Reverts avinash201199/To-Do-List#345
> Revert "Progress Tracker Bar Added"

- assets/css/style.css
- index.html
- Modern gradient-based UI design
- Enhanced statistics dashboard
- Quick filter system
- Import/Export functionality
- Priority system with visual indicators
- Due date support
- Tag system
- Responsive design
- 789 lines added, 79 lines modified
- Modern CSS with gradients and animations
- Responsive grid layouts
- Enhanced accessibility features
> Enhance To-Do List UI with improved styling and new features
